In [16]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import plotly.express as px
import pandas as pd

In [3]:
data = np.genfromtxt("output_vgg_features.txt")
data

array([[0.        , 0.41067803, 0.21798497, ..., 0.        , 0.        ,
        0.26835859],
       [0.        , 0.41060457, 0.21786821, ..., 0.        , 0.        ,
        0.26836771],
       [0.        , 0.41062963, 0.21794277, ..., 0.        , 0.        ,
        0.26837629],
       ...,
       [0.        , 0.41065654, 0.21786839, ..., 0.        , 0.        ,
        0.26834917],
       [0.        , 0.41064101, 0.21790102, ..., 0.        , 0.        ,
        0.26843393],
       [0.        , 0.4106774 , 0.21800473, ..., 0.        , 0.        ,
        0.26839224]])

In [8]:
data[:1]

array([[0.        , 0.41067803, 0.21798497, ..., 0.        , 0.        ,
        0.26835859]])

In [21]:
pca = PCA(n_components=3)
components = pca.fit_transform(data)
print(pca.explained_variance_ratio_)
total_var = pca.explained_variance_ratio_.sum() * 100

fig = px.scatter_3d(
    components, x=0, y=1, z=2,
    title=f'Total Explained Variance: {total_var:.2f}%',
    labels={'0': 'PC 1', '1': 'PC 2', '2': 'PC 3'}
)
fig.show()

[0.3440483  0.19797347 0.11709216]
